name: mito_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - fastqc
  - trimmomatic
  - velvet
  - blast
  - mafft
  - iqtree
  - gblocks
  - samtools
  - bedtools
  - seqkit
  - biopython
  - pandas
  - pip
  - r-base=4.3
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-ggsignif
  - r-phangorn
  - r-ape
  - r-optparse
  - r-rcolorbrewer
  - pip:
      - MitoZ==3.6
      - ete3
      - ncbi-entrez-direct==1.0.0
notes: |
  - If a package isn't available or your cluster uses modules, install tools there and adjust SLURM scripts.
  - MitoZ is installed via pip here; you may install it system-wide if preferred.
